- configure.ac
It seems that LTO is too problematic to enable at this point, in
particular mismatched tooling that otherwise can build a library fine
b0rks when encountering an unknown LTO object format.
> Remove LTO optimisation (should fix issue #12)

- src/Makefile.am
It's necessary to invoke node-gyp directly in order to pass the --debug
flag. I don't see any way of passing it via yarn install.
> Fix the js wrappers debug build

- include/wally.hpp
This works around warnings from container wrappers such as some gsl implementations which return ptrdiff_t (a signed type) for size().
> Cast C++ output container sizes to size_t

- .gitlab-ci.yml
- README.md
- contrib/Dockerfile
- contrib/Dockerfile_ubuntu
- contrib/stretch_deps.sh
- tools/android_helpers.sh
- tools/build_android_libraries.sh
This PR updates the ubuntu and Debian stretch to the latest versions and upgrades to ndk r18
Tested on GreenBits master.
> Update docker images, ndk and minor cleanup

- include/wally_crypto.h
- include/wally_script.h
- include/wally_transaction.h
- src/swig_python/python_extra.py_in
- src/test/test_script.py
- src/transaction.c
Low-R signatures are always 1 byte shorter, so allow callers to handle this to get exact (or at least much closer to exact) fee estimates.
Also fix the constant name for OP_RETURN scriptpubkey length.
> Add constant and flag for exact fee estimation with low-r signatures

- include/wally_transaction.h
- src/test/test_transaction.py
- src/transaction.c
Although transactions with version 0 or above the `CURRENT_VERSION` are not standard, it should be possible to serialize/deserialize them.
> Allow non standard transaction versions

- .gitlab-ci.yml
- README.md
- contrib/Dockerfile
- contrib/Dockerfile_ubuntu
- contrib/stretch_deps.sh
- tools/android_helpers.sh
- tools/build_android_libraries.sh
This updates the debian/ubuntu docker bases to latest packages for their LTS/stable versions and also updates the android ndk to r19
> update debian/ubuntu builders, ndk to r19

- setup.py
- src/secp256k1/Makefile.am
- src/secp256k1/configure.ac
- tools/build_android_libraries.sh
- tools/build_js_bindings.sh
this applies a secp fix from upstream https://github.com/bitcoin-core/secp256k1/pull/584 and an additional fix to enable ecmult-static-precomputation which is otherwise automatically on by default
It then explicitly enables ecmult-static-precomputation explicitly for all the artifacts (python, java ndk and js bindings) to avoid it silently not being enabled.
> Ecmult precomputation fix

- src/Makefile.am
- src/wrap_js/example.js
- src/wrap_js/makewrappers/templates/nan.py
- src/wrap_js/makewrappers/wrap.py
- src/wrap_js/test/test_bip32.js
- src/wrap_js/test/test_script.js
This builds on top of https://github.com/ElementsProject/libwally-core/pull/85
adds on top:
- code deduplication
- use of constants
- fix derivation labels
- use bip32_key_get_pub_key & bip32_key_get_priv_key instead of slice
- it removes one of the cases/examples as the generated address doesn't seem redeemable https://github.com/ElementsProject/libwally-core/pull/85/files#diff-8256341e9d6126fcdf265c5326cdc72bR43
- moves the example to a test
- some white space/semicolon fixes/unnecessary imports
> multisig addr nodejs

- README.md
Add list of projects and products that are known to depend on or use `libwally`.
Am I missing any known users? :-)
> docs: Add list of projects and products that are known to depend on or use libwally

- include/wally_address.h
- src/Makefile.am
- src/address.c
- src/swig_java/swig.i
- src/test/test_address.py
- src/test/util.py
- src/wrap_js/src/combined.c
Introduces function to derive a legacy (P2PKH) or wrapped SegWit (P2SH-P2WPKH) address from a BIP32 key:
```c
int wally_bip32_key_to_address(const struct ext_key *hdkey, uint32_t flags,
uint32_t version, char **output)
```
Implements #102 except for native SegWit, which I'll add a separate function for.
I did not add `c++` headers in `wally.hpp`.
I added tests in Python, but not for Javascript, Swig Python and Swig Java.
> Derive P2PKH, P2WPKH  and P2SH-P2WPKH address from BIP32 key

- include/wally_address.h
- src/address.c
- src/test/test_address.py
- src/test/util.py
My initial idea was to write a parser that can take either a base58 or bech32 address and return a `scriptPubKey`, with flags to constrain it to correct coin. However, to keep the change minimal, I'm using a approach that reuses `wally_addr_segwit_to_bytes` for bech32 and adds a new function for base58. A caller should either figure out themselves which address format they're dealing with, or simply try both functions. 
This PR adds `wally_address_to_scriptpubkey` to parse a base58 addresses (P2PKH and P2SH). It returns a `scriptPubKey` which can be used to create a transaction output.
A flag is used to set either Bitcoin mainnet or testnet. It then automatically figures out if this is a `P2PKH` or `P2SH` address. This approach requires additional `switch` cases to support other coins.
An …
> Parse address to scriptPubKey

- include/wally_bip32.h
- include/wally_core.h
- include/wally_psbt.h
- src/bip32.c
- src/test/test_bip32.py
- src/test/util.py
Adds a method `bip32_key_get_fingerprint` to get the fingerprint for a given key.
It's rather trivial, but it lets consumers of the library avoid touching `struct ext_key` internals. Particularly having access to the master fingerprint is quite useful, e.g. to compose output descriptors (#151) and to talk to a library like [HWI](https://github.com/bitcoin-core/HWI).
> Get bip32 fingerprint

- include/wally_address.h
It returns more than just the witness program.
> Clarify that wally_addr_segwit_from_bytes returns scriptPubKey

- include/wally_address.h
- src/address.c
- src/test/test_address.py
- src/test/util.py
Closes #118 
The new `wally_scriptpubkey_to_address` function could be expanded later to also work with SegWit, but I can't be bothered :-)
> Add wally_scriptpubkey_to_address

- src/psbt.c
I took me a while to find this issue, so I added two new error code `WALLY_ERROR_SCRIPTCODE_LEN` and `WALLY_ERROR_MATCH_WITNESS_PROGRAM_HASH` to make that a bit easier next time.
The current PSBT signing code, when spending from a non-p2sh output, tries to obtain the scriptPubKey from its own output (instead of the previous transaction's output):
https://github.com/ElementsProject/libwally-core/blob/dbb5e11a76fc4e09ad6381ce695f740bc536ed9b/src/psbt.c#L2595-L2596
This doesn't make any sense, and causes the following (mainnet) example PSBT to fail to sign (and fail with `WALLY_ERROR_MATCH_WITNESS_PROGRAM_HASH`):
```
Key (1 out of 2): KxDQjJwvLdNNGhsipGgmceWaPjRndZuaQB9B2tgdHsw5sQ8Rtqje
cHNidP8BAH0CAAAAAV/0Rj8kmS/ZB5NjsQvCKM1LTtovmhuQu2GITtz/XUFnAAAAAAD9////AqAPAAAAAAAAIgAg2SAanVpF/Lx6c7mjRV2 …
```
> PSBT: fix getting scriptPubKey for non-P2SH inputs

- src/wrap_js/cordovaplugin/yarn.lock
- src/wrap_js/yarn.lock
Update `yarn.lock` files for wallyjs and cordovaplugin removing vulnerabilities.
```bash
libwally-core/src/wrap_js: $ yarn audit                                                                           
yarn audit v1.15.2
0 vulnerabilities found - Packages audited: 218
✨  Done in 0.69s.
```
```bash
libwally-core/src/wrap_js/cordovaplugin: $ yarn audit
yarn audit v1.15.2
0 vulnerabilities found - Packages audited: 1470
✨  Done in 1.13s.
```
> Js updates

- src/transaction.c
This fixes psbt: in many places it assumes this behavior.  Older code carefully initializes to NULL before calling clone_bytes, so it's not broken by this change, but it's deeply surprising to new authors!
In particular, valgrind noticed the unitialized var in line 1665 in psbt.c:
if (input->final_script_sig) {
This is set in wally_psbt_input_set_final_script_sig:
unsigned char *result_final_script_sig;
if (!clone_bytes(&result_final_script_sig, final_script_sig, final_script_sig_len)) {
...
input->final_script_sig = result_final_script_sig;
Surprise, input->final_script_sig is now random garbage from the stack.
PSBT assumes similar behavior in other places: it seems easiest to fix the clone_bytes footgun rather than change all the psbt code.
Reported-by: @niftynei
Signed-off-by: Rusty …
> clone_bytes: set *dst to NULL if we are asked to clone a zero length value

- src/psbt.c
As written, this was looking at the output script on the global_tx for
an input on the same, which caused valgrind problems because A) there's
no guarantee that an output at that input index exists and also B)
that's not even the right script.
What you *want* to be doing is using the non_witness_utxo to look up the
script iff it exists.
If there's no out_script available we totally bail on finalizing this
input at all.
> psbt: fix broken script finder in wally_finalize_psbt

- src/bip32.c
Based on a patch by @k-matsuzawa
> bip32: Don't call privkey_tweak_add by empty tweakSum

- README.md
- src/Makefile.am
Also adds a trivial test that fails if any Java functions are not wrapped to prevent the Java wrappers from bit-rotting again.
> Docs update

- src/swig_python/swig.i
See commit for details. Now returns a message of the form:
````
TypeError: in method 'tx_to_hex', argument 1 of type '(wally_tx)'
````
If an invalid or wrong type of object is passed.
> SWIG Python: Fix handling of bad capsule pointers

- include/wally_transaction.h
- src/transaction.c
Merge branch for rangeproof sighash support from @k-matsuzawa (see https://github.com/ElementsProject/libwally-core/pull/270)
> Sighash rangeproof

- README.md
- configure.ac
- docs/source/conf.py
- include/wally_transaction.h
- setup.py
- src/transaction.c
- src/wrap_js/cordovaplugin/yarn.lock
Update cordova dependencies. Adds sighash rangeproof support (without tests, but since the code is conditional on the sighash flag, these can be added later).
> Bump version to 0.8.2

- .gitignore
This folder gets created since I bumped from 0.8.4 to 0.8.5, at least when using my own build script. See https://github.com/Sjors/libwally-swift/pull/62
> Add build-aux/ar-lib to .gitignore

- include/wally_bip32.h
- src/bip32.c
- src/test/test_bip32.py
Includes the bip32 mixed-hardened/non-hardened derivation fixes and upper case bip32 path changes from the descriptor PR, plus adds a couple more test cases from @JamieDriver
> Bip32 updates

- contrib/shell_minimal.html
To be compatible with the emcc `MODULARIZE` setting, which made `ccall()` scoped under `Module`.
> wasm: Fix the shell_minimal example

- src/pyexample/liquid/receive-send.py
The example is very helpful for explaining CT in Liquid as well as the API in libwally.
This MR clarifies that an asset commitment is stored in a CT transaction output (not an asset), and that an asset commitment is also a generator.
> Rename variable to clarify asset commitments and generator

- include/wally_crypto.h
- src/sign.c
- src/test/test_sign.py
secp was incorrectly reverted when merging the previous commit.
This enables caller use of the aux_rand secp feature for ECDSA, which can be used e.g. for manual grinding.
> sign: support aux data for ECDSA, docs fixes, fix secp version

- _CMakeLists.txt
- _cmake/config.h.in
- _cmake/utils.cmake
First introduction of cmake to generate the config.h file, mirroring the config.h file genrated by autoheader
FYI: @k-matsuzawa 
``_cmake`` folder and main ``CMakeLists.txt`` file are intentionally prefixed with ``_`` to avoid possible conflicts to any 3rd parties who forked the project to implement their own cmake build system.
As the cmake introduction in this repository will be incremental, we would like to create the least amount of disruption to others
> build-system: cmake generating config.h

- src/ccan_config.h
- src/descriptor.c
- src/internal.c
- Fix alignment checks for hashes which would slightly pessimize strong alignment targets.
- Align pk_h hash output for better hash performance.
- Mark arm 32bit as not supporting unaligned access.
The last commit fixes a crash on Rasbian reported by @jmastr, thanks for the bug report!
Fixes https://github.com/ElementsProject/libwally-core/issues/396
> Alignment changes

- src/ctest/test_psbt_limits.c
- src/internal.c
- src/internal.h
- src/psbt.c
- src/transaction.c
- unilaterally force a memory barrier for memory clearing
- fix test_psbt_limits compilation under msvcrt
- clamp initial pre-allocation sizes to prevent DOS
> Misc updates

- _CMakeLists.txt
- _cmake/libsecp256k1-pkgconfig.cmake
- _cmake/libsecp256k1.cmake
- _cmake/wallycore-config.cmake.in
- src/_CMakeLists.txt
Extending cmake to compile wallycore source files into a native library
- libsecp256k1 is compiled using ExternalProject cmake module
- ccan sources are compiled as OBJECT libraries
This commit also introduces a first draft of the install process where wallycore library and include files are installed together with the libsecp256k1 ones.
cmake target files are also installed, so users can import wallycore library using cmake's find_package tools.
As libsecp256k1 is an automake-based project we massage its .pc to fit the cmake install process
In cmake language, users can now do
```
find_package(wallycore COMPONENTS wallycore libsecp256k1)
```
and then target the libraries as
```
target_link_libraries(<myproject> [PRIVATE|PUBLIC]
wallycore::wallycore
wallycore::libsecp256k1
)
```
FYI: …
> build-system: compile libsecp and wallycore with cmake

- configure.ac
The POSIX Shell `test` built-in does not define a `==` operator. It works if `/bin/sh` happens to be Bash, but that is non-standard.
@jgriffiths: Since you're planning a 1.0.0 release, now would be a good time to fix this so I can finally discontinue patching it downstream.
> configure.ac: fix Bashisms

- configure.ac
SWIG generates code with unused parameters that trigger hundreds of warnings.
> add `-Wno-unused-parameter` to `SWIG_WARN_CFLAGS`

- src/Makefile.am
version-info is what determines the dotted triplet of numbers trailing the shared library filename. Meticulous maintenance of version-info allows multiple ABI versions of the library to be installed on a system concurrently and also makes obvious when library clients need to be recompiled for a newer ABI (and when no recompilation is necessary).
See: https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html
> add `-version-info` to `LDFLAGS` in shared library builds

- configure.ac
Quoting jgriffiths:
> `--enable-openssl-tests` is no longer supported in secp and should be removed
Suggested-by: @jgriffiths
See: https://github.com/ElementsProject/libwally-core/pull/414#discussion_r1312347724
> drop `--enable-openssl-tests` from libsecp256k1 config

- include/wally_bip39.h
- src/bip39.c
> bip39: expose a non-allocating bip39_get_word_by_index

- .github/workflows/wasm-package.yml
- .gitlab-ci.yml
- CHANGES.md
- README.md
- contrib/Dockerfile_bullseye
- contrib/bullseye_deps.sh
- contrib/requirements.txt
- include/wally_descriptor.h
- src/aes.c
- src/bip32.c
- src/internal.c
- src/psbt.c
- src/test/test_transaction.py
- src/wasm_package/build.sh
- tools/build_android_libraries.sh
- tools/cleanup.sh
- tools/update_wasm_package.sh
Fix readthedocs, prevent node 16 EOL warning from github, JS build updates, internal CI updates.
> Post 1.1.0 updates

- .github/workflows/wheels.yml
- src/psbt.c
- src/transaction.c
Allow as many inputs/outputs as are present if we are building a tx from its serialized bytes. Since we fully analyze the tx before building it, we know that it can fit in memory/is not impossible to create for DOS checking purposes. This allows us to process live txs such as a recent testnet tx with ~100k outputs.
We retain the limit on constructing new txs from scratch, since wally is meant only for making txs that fit within standardness rules. This catches cases where a tx is constructed in parts or allocated up front based on an externally provided number of inputs/ouputs.
Update the comments to reflect that the limits are for standardness and not block size.
> tx: check absolute tx limits only when constructing from scratch

- CHANGES.md
- include/wally_psbt.h
- src/psbt.c
Following this change, wally is able to generate proofs even if only a non-witness UTXO is present.
> PSET: Allow proof generation for PSET inputs without witness UTXOs

- .gitlab-ci.yml
- contrib/Dockerfile_bullseye
- contrib/bullseye_deps.sh
Modified version of the PR from @DeviaVir here https://github.com/ElementsProject/libwally-core/pull/465
> Docker updates, arm64 support

- docs/source/conf.py
- setup.py
- src/ctest/test_descriptor.c
- src/descriptor.c
- src/pullpush.c
- src/swig_python/contrib/elements_tx.py
- src/swig_python/contrib/mnemonic.py
- src/swig_python/contrib/psbt.py
- src/swig_python/contrib/reconcile_sigs.py
- src/swig_python/contrib/signmessage.py
- src/swig_python/contrib/tx.py
- src/test/test_aes.py
- src/test/test_anti_exfil.py
- src/test/test_elements.py
- src/test/test_map.py
- src/test/test_sign.py
- src/test/test_transaction.py
- src/test/util.py
- tools/build_wrappers.py
- tools/wordlist_cc.py
Adds `rawtr()` and `tr(k)` initially, as the simplest of the taproot descriptor cases.
`tr(k,script)` will be added in a future MR.
> Misc cleanups, add rawtr()/tr(k) descriptor support

- include/wally_transaction.h
- src/psbt.c
- src/transaction.c
- src/tx_io.c
This completes moving signature hash generation to the new, caching interface. Although pre-segwit transactions do not benefit from caching, the new impl is cleaner and uses less stack. Additionally, it allows removing all signature hash generation code from the transaction serialization code, making it easier to reason about.
> Update pre-segwit signature hashing to use the new caching implementation

- src/ctest/test_descriptor.c
- src/descriptor.c
Fixes https://github.com/ElementsProject/libwally-core/issues/486
> descriptor: allow U type children for thresh() expressions

- src/address.c
- src/test/test_address.py
Account for regtest using the same (non-segwit) address prefix as testnet.
> address_to_scriptpubkey: correctly handle WALLY_NETWORK_BITCOIN_REGTEST

- src/ccan/ccan/compiler/compiler.h
- src/ccan/ccan/crypto/sha256/sha256.c
- src/ccan/ccan/crypto/sha256/sha256_sse4.c
- src/ccan/ccan/crypto/sha512/sha512.c
- src/tx_io.c
Cleanups for the ccan sha code and a fix for tx_io hashing for non-default sha256 implementations (affecting taproot txs with more than 1 taproot input).
> Mbed sha256
